# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ordeal < Formula
  desc "Adversarial test harness for Sigma detection rules"
  homepage "https://principlebreach.com"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/principlebreach/ordeal/releases/download/v0.1.1/ordeal_0.1.1_darwin_amd64.tar.gz"
      sha256 "e993d04d304527f430b50922d6c80ddbf5a68ce81e266a89165edc0202c32be2"

      define_method(:install) do
        bin.install "ordeal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/principlebreach/ordeal/releases/download/v0.1.1/ordeal_0.1.1_darwin_arm64.tar.gz"
      sha256 "6f0e1c5a728be0b8d84e2514fffa843b4a7dfb2a223be483785cd6bc519f6955"

      define_method(:install) do
        bin.install "ordeal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/principlebreach/ordeal/releases/download/v0.1.1/ordeal_0.1.1_linux_amd64.tar.gz"
      sha256 "723a10f2d12af45b1b5029386f06826f3c26b7d06f876aec15e71462382a9b79"
      define_method(:install) do
        bin.install "ordeal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/principlebreach/ordeal/releases/download/v0.1.1/ordeal_0.1.1_linux_arm64.tar.gz"
      sha256 "ae8cdffe27dc2d39a9e6520fc29b61c1ee8e598b24e3f31e1328a29c581d5850"
      define_method(:install) do
        bin.install "ordeal"
      end
    end
  end

  test do
    system "#{bin}/ordeal", "--version"
  end
end
